### ISSUE TITLE
Can't build ss-server

### ISSUE THREAD

**Issue by cjl3230** [shadowsocksr-backup/shadowsocksr-libev#7]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
e2373d7199102f383b741da148b989c7c1e8832e

### What operating system are you using?
CentOS 6.x 64bit

### What did you do?
compile ss-server, I found commit "Don't compile ss-manager ss-server and ss-tunnel", but how can i use ss-server?

### What did you expect to see?
compile ss-server successful

### What did you see instead?
compile successful but no ss-server ss-manager ss-tunnel

### What is your config in detail (with all sensitive info masked)?
none

**Comment by RichieMay** [comment]
为什么要把ss-manager ss-server and ss-tunnel这几个从编译中去掉呢，代码log完全看不出来原因！去掉了那么现在怎么编译呢？主版本库应该随时保证最新代码能够没有问题，这是每个开发人员都应该牢记的东西！
